fallback = 'ï‹'
separator = ' '

[matching]
'discord' = 'ï’'
'balena-etcher' = 'ï‹›'
'Chia Blockchain' = 'ï“˜'
'Steam' = 'ï†¶'
'vlc' = 'ï€½'
'org.qbittorrent.qBittorrent' = 'ï¶'
'Thunderbird' = 'ïƒ '
'thunderbird' = 'ïƒ '
'Postman' = 'ï '
'Insomnia' = 'ïˆ¶'
'Bitwarden' = 'ï‚„'
'Google-chrome' = 'ï‰¨'
'google-chrome' = 'ï‰¨'
'Chromium' = 'ï‰¨'
'Slack' = 'ï†˜'
'Code' = 'ï„¡'
'code-oss' = 'ï„¡'
'jetbrains-studio' = 'ï„¡'
'Spotify' = 'ï†¼'
'GitHub Desktop' = 'ï„“'
# '/(?i)Github.*Firefox/' = 'ï„“'
'/firefox|Firefox/' = 'ï‰©'
# '/irefox */' = 'L'
'Nightly' = 'ï‰©'
'firefoxdeveloperedition' = 'ï‰©'
'/nvim ?\w*/' = 'ï‰½'
'/npm/' = 'ï¹'
'/node/' = 'ï¹'
'/yarn/' = 'ï¹'
'Alacritty' = 'ï„ '
'sioyek' = 'ğŸ—'
'evince' = 'ğŸ—'
# 'foot' = 'ğŸ‘£'
'/zip/' = 'ï†‡'
'/md/' = 'ï’Š'
'/ranger/' = 'ğŸ•¶'
